"""Color DevOps Agent Team — core coordinator, task state machine,
team/agent registry, and structured event log (Phase 1).

The package depends only on the Python standard library. It records every
task transition as an immutable, durable event; a restarted coordinator
replays the event log and never duplicates a completed transition.
"""

from .registry import (
    APPROVER_ROLES,
    CapabilityNotAllowedError,
    DuplicateAgentError,
    RegistrationError,
    RoleNotAllowedError,
    TeamRegistry,
    UnknownRoleError,
    UnknownTeamError,
)
from .coordinator import Coordinator
from .risk import RiskClass
from .ledger import (
    EvidenceLedger,
    EvidenceRecord,
    IncompleteEvidenceError,
    LedgerError,
    LedgerImmutableError,
)
from .governance import (
    ApprovalRecord,
    GovernanceError,
    NoSelfApprovalError,
    RiskRegressionError,
    RoleRequiredError,
    ScopeApprovalRequired,
    ScopeDeclaration,
    ScopeNotDeclaredError,
    WhiteTeam,
    scope_covers,
)
from .secrets import SecretExposureError
from .scope import ScopeOutOfBoundsError, validate_scope
from .watchdog import Watchdog
from .observer import (
    FORBIDDEN_INTERPRETATION_KEYS,
    OBSERVATION_TYPES,
    InterpretationInObservationError,
    Observation,
    ObservationTypeError,
    Observer,
    ObserverError,
)
from .blue import (
    Alert,
    AlertConditionError,
    BlueTeam,
    BlueTeamError,
    NoEvidenceError,
    Recommendation,
    RunbookEntry,
    UnauthorizedActorError,
)
from .black import (
    BlackNoEvidenceError,
    BlackNoUncertaintyError,
    BlackTeam,
    BlackTeamError,
    BlackUnauthorizedActorError,
    CONFIDENCE_LEVELS,
    Diagnosis,
    Experiment,
    Hypothesis,
    InvalidInputError,
)
from .silver import (
    ChangeManifest,
    InvalidImplementationError,
    SecretInImplementationError,
    SILVER_CHANGE_TYPES,
    SilverNoEvidenceError,
    SilverTeam,
    SilverTeamError,
    SilverUnauthorizedActorError,
)
from .yellow import (
    CHECK_TYPES,
    InvalidCheckError,
    SelfApprovalError,
    VerificationResult,
    YellowNoEvidenceError,
    YellowTeam,
    YellowTeamError,
    YellowUnauthorizedActorError,
)
from .red import (
    FINDING_SEVERITIES,
    Finding,
    InvalidFindingError,
    RedDestructiveTestRefusedError,
    RedTeam,
    RedTeamError,
    RedUnauthorizedActorError,
    RedUnspecifiedTargetError,
)
from .purple import (
    CLOSURE_VERDICTS,
    Closure,
    InvalidClosureError,
    PurpleNoReTestError,
    PurpleTeam,
    PurpleTeamError,
    PurpleUnauthorizedActorError,
)
from .gold import (
    ExceptionGrant,
    ExceptionRequiresApproval,
    GoldTeam,
    GoldTeamError,
    GoldUnauthorizedActorError,
    InvalidExceptionError,
    InvalidStandardError,
    ReferencePipeline,
    Standard,
    UnboundedExceptionRefusedError,
    VersionConflictError,
    VERSION_RE,
)
from .green import (
    GreenReleaseNotApproved,
    GreenRollbackPlanRequired,
    GreenTeam,
    GreenTeamError,
    GreenUnauthorizedActorError,
    InvalidReleasePlanError,
    InvalidRollbackError,
    Release,
    ReleasePlan,
    Rollback,
)

__all__ = [
    "Coordinator",
    "TeamRegistry",
    "RegistrationError",
    "UnknownTeamError",
    "DuplicateAgentError",
    "CapabilityNotAllowedError",
    "UnknownRoleError",
    "RoleNotAllowedError",
    "APPROVER_ROLES",
    "RiskClass",
    "EvidenceLedger",
    "EvidenceRecord",
    "LedgerError",
    "IncompleteEvidenceError",
    "LedgerImmutableError",
    "WhiteTeam",
    "ApprovalRecord",
    "ScopeDeclaration",
    "GovernanceError",
    "NoSelfApprovalError",
    "RiskRegressionError",
    "RoleRequiredError",
    "ScopeApprovalRequired",
    "ScopeNotDeclaredError",
    "scope_covers",
    "SecretExposureError",
    "ScopeOutOfBoundsError",
    "validate_scope",
    "Watchdog",
    "Observer",
    "ObserverError",
    "ObservationTypeError",
    "InterpretationInObservationError",
    "Observation",
    "OBSERVATION_TYPES",
    "FORBIDDEN_INTERPRETATION_KEYS",
    "BlueTeam",
    "BlueTeamError",
    "Alert",
    "AlertConditionError",
    "Recommendation",
    "RunbookEntry",
    "NoEvidenceError",
    "UnauthorizedActorError",
    "BlackTeam",
    "BlackTeamError",
    "BlackNoEvidenceError",
    "BlackNoUncertaintyError",
    "BlackUnauthorizedActorError",
    "CONFIDENCE_LEVELS",
    "Hypothesis",
    "Experiment",
    "Diagnosis",
    "InvalidInputError",
    "SilverTeam",
    "SilverTeamError",
    "SilverNoEvidenceError",
    "SilverUnauthorizedActorError",
    "SecretInImplementationError",
    "InvalidImplementationError",
    "ChangeManifest",
    "SILVER_CHANGE_TYPES",
    "YellowTeam",
    "YellowTeamError",
    "YellowNoEvidenceError",
    "YellowUnauthorizedActorError",
    "InvalidCheckError",
    "SelfApprovalError",
    "VerificationResult",
    "CHECK_TYPES",
    "RedTeam",
    "RedTeamError",
    "RedUnauthorizedActorError",
    "RedUnspecifiedTargetError",
    "RedDestructiveTestRefusedError",
    "Finding",
    "FINDING_SEVERITIES",
    "InvalidFindingError",
    "PurpleTeam",
    "PurpleTeamError",
    "PurpleUnauthorizedActorError",
    "PurpleNoReTestError",
    "Closure",
    "CLOSURE_VERDICTS",
    "InvalidClosureError",
    "GoldTeam",
    "GoldTeamError",
    "GoldUnauthorizedActorError",
    "InvalidStandardError",
    "VersionConflictError",
    "InvalidExceptionError",
    "ExceptionRequiresApproval",
    "UnboundedExceptionRefusedError",
    "Standard",
    "ReferencePipeline",
    "ExceptionGrant",
    "VERSION_RE",
    "GreenTeam",
    "GreenTeamError",
    "GreenUnauthorizedActorError",
    "GreenRollbackPlanRequired",
    "GreenReleaseNotApproved",
    "InvalidReleasePlanError",
    "InvalidRollbackError",
    "ReleasePlan",
    "Release",
    "Rollback",
]
